#
# This is the Travis-CI configuration.
#
# The actual dependency installation and test execution is done via tox as a
# way to share the same process between Travis-CI and Buildbot.
#
language: python
sudo: false


# Only run tests on push on a few branches.
# Test on PR should be execute for all branches and forks.
branches:
  only:
  - master


env:
  global:
    - TRIAL_REPORTER=text


matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-withcov,codecov-publish
    - python: 3.3
      env: TOXENV=py33-withcov,codecov-publish
    - python: 3.4
      env: TOXENV=py34-withcov,codecov-publish
    - python: 3.5
      env: TOXENV=py35-withcov,codecov-publish
    # For now all non-trial tests are in a single job to reduce the time spent
    # on starting separate jobs.
    - python: 2.7
      env: TOXENV=pyflakes,manifest-checker


cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv


install:
  - ./.travis/install.sh tox


# Run tox from the created virtualenv.
script:
  - ./.travis/run.sh
